# Generated by Django 5.2.13 on 2026-04-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payoutengine', '0002_alter_bankaccount_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='payoutengine.merchant'),
        ),
    ]
